name: C# Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Mono
      run: sudo apt-get install -y mono-complete

    - name: Compile C# files
      run: mcs -t:library *.cs

    - name: Syntax Check
      run: csc -target:library -warn:4 *.cs
