name: ASP.NET Core CI

on:
  push:
    branches:
      - main

jobs:
  check_style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install StyleCopAnalyzers
        run: dotnet add QrGraduationAdmin/QrGraduationAdmin.csproj package StyleCop.Analyzers --version 1.2.0-beta.556

      - name: Check code style
        run: |
          cd QrGraduationAdmin
          dotnet build /p:StyleCopEnabled=true /p:StyleCopConfig=.stylecop.json
