name: ASP.NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Укажите нужную версию .NET Core SDK

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Check for syntax errors
      run: |
        # Запускаем dotnet build, сохраняя вывод в файл
        dotnet build --configuration Release > build.log
        
        # Ищем строки, содержащие "error" в файле с выводом сборки
        if grep -iq 'error' build.log; then
          echo "Syntax errors found!"
          exit 1
        else
          echo "No syntax errors found."
        fi
